/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author thoma
 */
public class Configuracao extends javax.swing.JFrame {

    /**
     * Creates new form Configuracao
     */
    public Configuracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConfiguracao = new javax.swing.JPanel();
        campoFileMemoria = new javax.swing.JTextField();
        textoMemoria = new javax.swing.JLabel();
        tituloConfiguracao = new javax.swing.JLabel();
        botaoBuscarMemoria = new javax.swing.JButton();
        textoCache = new javax.swing.JLabel();
        campoFileCache = new javax.swing.JTextField();
        botaoBuscarCache = new javax.swing.JButton();
        botaoBuscarInstrucoes = new javax.swing.JButton();
        campoFileInstrucoes = new javax.swing.JTextField();
        textoInstrucoes = new javax.swing.JLabel();
        botaoConfigurar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuraçoes Iniciais - Simulador");
        setResizable(false);

        textoMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMemoria.setText("Memória Principal");

        tituloConfiguracao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloConfiguracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloConfiguracao.setText("Simulador de Memória Cache - Configurações Iniciais");

        botaoBuscarMemoria.setText("Buscar");
        botaoBuscarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarMemoriaActionPerformed(evt);
            }
        });

        textoCache.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCache.setText("Configuração Cache");

        botaoBuscarCache.setText("Buscar");
        botaoBuscarCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCacheActionPerformed(evt);
            }
        });

        botaoBuscarInstrucoes.setText("Buscar");
        botaoBuscarInstrucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarInstrucoesActionPerformed(evt);
            }
        });

        textoInstrucoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInstrucoes.setText("Instruções");

        botaoConfigurar.setText("Configurar");
        botaoConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfigurarActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConfiguracaoLayout = new javax.swing.GroupLayout(painelConfiguracao);
        painelConfiguracao.setLayout(painelConfiguracaoLayout);
        painelConfiguracaoLayout.setHorizontalGroup(
            painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                        .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCache, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConfiguracaoLayout.createSequentialGroup()
                                .addComponent(campoFileMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(botaoBuscarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(146, 146, 146)
                                    .addComponent(botaoConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                                    .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoFileCache, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(campoFileInstrucoes))
                                    .addGap(10, 10, 10)
                                    .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoBuscarCache, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoBuscarInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                        .addComponent(tituloConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        painelConfiguracaoLayout.setVerticalGroup(
            painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFileMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCache, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFileCache, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscarCache, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscarInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFileInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(painelConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Configuracoes");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarInstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarInstrucoesActionPerformed
        JFileChooser buscarArquivo = new JFileChooser();
        buscarArquivo.setDialogTitle("Buscar Arquivo - Instruções");
        buscarArquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos de texto", "txt");
        buscarArquivo.setFileFilter(filtro);
        buscarArquivo.showOpenDialog(this);
    }//GEN-LAST:event_botaoBuscarInstrucoesActionPerformed

    private void botaoBuscarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarMemoriaActionPerformed
        JFileChooser buscarArquivo = new JFileChooser();
        buscarArquivo.setDialogTitle("Buscar Arquivo - Memória Principal");
        buscarArquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos de texto", "txt");
        buscarArquivo.setFileFilter(filtro);
        buscarArquivo.showOpenDialog(this);
    }//GEN-LAST:event_botaoBuscarMemoriaActionPerformed

    private void botaoConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfigurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfigurarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoBuscarCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCacheActionPerformed
        JFileChooser buscarArquivo = new JFileChooser();
        buscarArquivo.setDialogTitle("Buscar Arquivo - Memória Cache");
        buscarArquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos de texto", "txt");
        buscarArquivo.setFileFilter(filtro);
        buscarArquivo.showOpenDialog(this);
    }//GEN-LAST:event_botaoBuscarCacheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarCache;
    private javax.swing.JButton botaoBuscarInstrucoes;
    private javax.swing.JButton botaoBuscarMemoria;
    private javax.swing.JButton botaoConfigurar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextField campoFileCache;
    private javax.swing.JTextField campoFileInstrucoes;
    private javax.swing.JTextField campoFileMemoria;
    private javax.swing.JPanel painelConfiguracao;
    private javax.swing.JLabel textoCache;
    private javax.swing.JLabel textoInstrucoes;
    private javax.swing.JLabel textoMemoria;
    private javax.swing.JLabel tituloConfiguracao;
    // End of variables declaration//GEN-END:variables
}
